application-version: '@project.version@'
application-description: '@project.description@'
server:
  port: ${SERVER_PORT:8081}

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: @activatedProperties@
  application:
    name: ${SPRING_APPLICATION_NAME:ms-usuarios}

  datasource:
    url: ${USUARIOS_DB_URL:jdbc:postgresql://localhost:5432/usuario_database?currentSchema=usuarios_nuevo}
    username: ${USUARIOS_DB_USERNAME:postgres}
    password: ${USUARIOS_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://keycloakqa.apps.gob.bo/realms/test}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:https://keycloakqa.apps.gob.bo/realms/test/protocol/openid-connect/certs}
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:ms-usuarios-local}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:change_me}
            authorization-grant-type: ${KEYCLOAK_AUTH_GRANT_TYPE:client_credentials}
            scope: ${KEYCLOAK_SCOPE:openid}
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:https://keycloakqa.apps.gob.bo/realms/test}
logging:
  level:
    org:
      keycloak: DEBUG
      springframework:
        security: DEBUG


eureka:
  client:
    fetch-registry: ${EUREKA_FETCH_REGISTRY:true}
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:true}
    registry-fetch-interval-seconds: ${EUREKA_REGISTRY_FETCH_INTERVAL_SECONDS:5}
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka:password@localhost:8761/eureka}

keycloak-client:
  server-url: ${KEYCLOAK_SERVER_URL:https://keycloakqa.apps.gob.bo}
  realm: ${KEYCLOAK_REALM:test}
  client: ${KEYCLOAK_ADMIN_CLIENT:admin-java}
  client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:change_me}
