application-version: '@project.version@'
application-description: '@project.description@'
server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:ms-usuarios}
  #  cloud:
  #    config:
  #      profile: default
  rabbitmq:
    port: ${RABBITMQ_PORT:5672}
    host: ${RABBITMQ_HOST:rabbitmqa.qapruebas.svc.cluster.local}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:change_me}
    exchange: ${RABBITMQ_EXCHANGE:topic-exchange}
    user-queue: ${RABBITMQ_USER_QUEUE:usuario.queue}
    routing-key: ${RABBITMQ_ROUTING_KEY:usuario.#}
    virtual-host: ${RABBITMQ_VHOST:/}
  config:
    import: optional:file:.env.staging[.properties],optional:file:.env[.properties],optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  datasource:
    password: ${STAGING_DB_PASSWORD:postgres}
    username: ${STAGING_DB_USERNAME:postgres}
    url: ${STAGING_DB_URL:jdbc:postgresql://localhost:5432/usuario_database}
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://keycloakqa.apps.gob.bo/realms/test}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:https://keycloakqa.apps.gob.bo/realms/test/protocol/openid-connect/certs}

logging:
  level:
    org:
      keycloak: INFO

eureka:
  client:
    fetch-registry: ${EUREKA_FETCH_REGISTRY:true}
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:true}
    registry-fetch-interval-seconds: ${EUREKA_REGISTRY_FETCH_INTERVAL_SECONDS:5}
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka:password@discovery-server:8761/eureka}

keycloak-client:
  server-url: ${KEYCLOAK_SERVER_URL:https://keycloakqa.apps.gob.bo}
  realm: ${KEYCLOAK_REALM:test}
  client: ${KEYCLOAK_ADMIN_CLIENT:admin-java}
  client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:change_me}
